# Generated by Django 4.2.15 on 2025-04-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_cv_parser", "0002_cvrewritesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedcv",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="parsedcv",
            name="temp_file_path",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
