# Generated by Django 4.2.15 on 2025-04-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_cv_parser", "0003_parsedcv_extracted_text_parsedcv_temp_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedcv",
            name="analysis_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parsedcv",
            name="analysis_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="parsedcv",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
