# Generated by Django 4.2.15 on 2025-04-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_cv_parser", "0004_parsedcv_analysis_data_parsedcv_analysis_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedcv",
            name="file_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
