# Generated by Django 4.2.15 on 2025-04-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_cv_parser", "0005_parsedcv_file_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parsedcv",
            name="file_type",
        ),
        migrations.AddField(
            model_name="cvrewritesession",
            name="cv_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
