# Generated by Django 4.2.15 on 2025-10-07 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_cv_parser", "0010_add_result_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedcv",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parsedcv",
            name="is_guest",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="parsedcv",
            name="session_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="parsedcv",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_parsed_cvs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
