# Generated by Django 4.2.15 on 2025-10-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_cv_parser", "0011_parsedcv_expires_at_parsedcv_is_guest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "verification_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField()),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("link_clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parsed_cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to="ai_cv_parser.parsedcv",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification",
                "verbose_name_plural": "Email Verifications",
                "db_table": "email_verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "is_verified"],
                        name="email_verif_email_9710ff_idx",
                    ),
                    models.Index(
                        fields=["verification_token"],
                        name="email_verif_verific_9a94bc_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="email_verif_created_3e4d2c_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="email_verif_expires_fdd67c_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="emailverification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_verified", True)),
                fields=("email",),
                name="unique_verified_cv_email",
            ),
        ),
    ]
