# Generated by Django 4.2.15 on 2025-11-02 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_cv_parser", "0012_emailverification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedcv",
            name="ai_model_used",
            field=models.CharField(
                blank=True,
                help_text="AI model used for generation/improvement",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="parsedcv",
            name="original_parsed_cv",
            field=models.ForeignKey(
                blank=True,
                help_text="Original CV this is an improved version of",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="improved_versions",
                to="ai_cv_parser.parsedcv",
            ),
        ),
        migrations.AddField(
            model_name="parsedcv",
            name="quality_score",
            field=models.FloatField(
                blank=True, help_text="Quality score from 3-Layer QC", null=True
            ),
        ),
        migrations.AddField(
            model_name="parsedcv",
            name="user_rating",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                help_text="User rating 1-5 (for future LLM training)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parsedcv",
            name="version_number",
            field=models.IntegerField(
                default=1, help_text="Version number in rewrite chain"
            ),
        ),
    ]
