# Generated by Django 4.2.15 on 2025-11-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_cv_parser",
            "0013_parsedcv_ai_model_used_parsedcv_original_parsed_cv_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedcv",
            name="template",
            field=models.CharField(
                blank=True,
                default="executive",
                help_text="Selected CV template (executive, modern, tech-focus, etc.)",
                max_length=50,
            ),
        ),
    ]
