# Generated by Django 4.2.15 on 2025-11-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_cv_parser", "0014_add_template_to_parsed_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsedcv",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Whether this is the user's primary/default CV"
            ),
        ),
    ]
