services:
  - type: web
    name: ella-backend
    env: python
    plan: free
    branch: new-main
    buildCommand: "./bin/custom_build.sh"
    startCommand: "./bin/start_gunicorn.sh"
    healthCheckPath: /api/health/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ella_writer.settings
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: www.ellacvwriter.com,ellacvwriter.com,ella-backend-gw8c.onrender.com,www.ellacv.com,ellacv.com,ellacvwriter.vercel.app,www.ellacvwriter.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://www.ellacvwriter.com,https://ellacvwriter.com,https://www.ellacv.com,https://ellacv.com,https://ellacvwriter.vercel.app,https://www.ellacvwriter.vercel.app
      - key: FRONTEND_URL
        value: https://ellacv.com
      - key: DATABASE_URL
        fromDatabase:
          name: ella-postgres
          property: connectionString
      - key: MISTRAL_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: "8000"
      - key: DEEPSEEK_TIMEOUT
        value: "100"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "true"

databases:
  - name: ella-postgres
    plan: free
    region: oregon
