services:
  - type: web
    name: ella-backend
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate
      gunicorn ella_writer.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ella_writer.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: ella-postgres
          property: connectionString
      - key: ALLOWED_HOSTS
        value: project3-backend-7ck4.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://project3-backend-7ck4.onrender.com,https://ellacvwriter.com

databases:
  - name: ella-postgres
    plan: free
    region: oregon
    ipAllowList: []