services:
  - type: web
    name: ella-backend
    env: python
    plan: free
    branch: main
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn ella_writer.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ella_writer.settings
      - key: DEBUG
        value: False
      - key: DJANGO_DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: www.ellacvwriter.com,ellacvwriter.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://www.ellacvwriter.com,https://ellacvwriter.com
      - key: DATABASE_URL
        fromDatabase:
          name: ella-postgres
          property: connectionString
      - key: MISTRAL_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

databases:
  - name: ella-postgres
    plan: free
    region: oregon