# Generated by Django 4.2.15 on 2025-03-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = []
