# Generated by Django 4.2.15 on 2025-03-20 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscription", "0002_auto_20250320_0646"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_ai_interview_prep",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_cv_analytics",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_job_alerts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_priority_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="interval",
            field=models.CharField(
                choices=[("month", "Monthly"), ("year", "Yearly")],
                default="month",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_cv_generations",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_job_applications",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_saved_jobs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="slug",
            field=models.CharField(default="example", max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_price_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_product_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField()),
                ("cv_generations_used", models.IntegerField(default=0)),
                ("job_applications_used", models.IntegerField(default=0)),
                ("saved_jobs_count", models.IntegerField(default=0)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscription.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        # Removed potentially problematic AlterField and DeleteModel operations
    ]
