# Generated by Django 4.2.15 on 2025-03-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_add_annual_price_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this feature is available in this plan",
                    ),
                ),
                (
                    "value_limit",
                    models.CharField(
                        blank=True,
                        help_text="Limit value for this feature, if applicable",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan Feature",
                "verbose_name_plural": "Plan Features",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier or class", max_length=50
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this feature should be highlighted in plan comparisons",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Order in which to display the feature"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Feature",
                "verbose_name_plural": "Subscription Features",
                "ordering": ["display_order", "name"],
            },
        ),
        # Removing these operations since the fields don't exist
        # migrations.RemoveField(
        #     model_name="subscriptionplan",
        #     name="duration_days",
        # ),
        # migrations.RemoveField(
        #     model_name="subscriptionplan",
        #     name="is_active",
        # ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_popular",
            field=models.BooleanField(
                default=False, help_text="Indicates if this is a featured/popular plan"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Brief description displayed in plan cards",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="featureusage",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_usage",
                to="subscription.usersubscription",
            ),
        ),
        # This field might not exist in the database schema
        # migrations.RemoveField(
        #     model_name="subscriptionplan",
        #     name="features",
        # ),
        migrations.AlterField(
            model_name="subscriptionusagelog",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_logs",
                to="subscription.usersubscription",
            ),
        ),
        # This model likely doesn't exist in the database
        # migrations.DeleteModel(
        #     name="Subscription",
        # ),
        migrations.AddField(
            model_name="planfeature",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.subscriptionfeature",
            ),
        ),
        migrations.AddField(
            model_name="planfeature",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="features",
            field=models.ManyToManyField(
                related_name="plans",
                through="subscription.PlanFeature",
                to="subscription.subscriptionfeature",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planfeature",
            unique_together={("plan", "feature")},
        ),
    ]
