# Generated by Django 4.2.15 on 2025-03-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_planfeature_subscriptionfeature_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="is_active",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
