# Generated by Django 4.2.15 on 2025-01-31 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=255)),
                ('employer_website', models.URLField(blank=True, null=True)),
                ('is_nonprofit', models.BooleanField(default=False)),
                ('charity_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Job'), ('volunteer', 'Volunteer')], default='job', max_length=20)),
                ('mode', models.CharField(choices=[('on_site', 'On Site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20)),
                ('time_commitment', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('flexible', 'Flexible'), ('one_off', 'One Off'), ('occasional', 'Occasional')], max_length=20)),
                ('experience_level', models.CharField(choices=[('entry_level', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director'), ('executive', 'Executive'), ('no_experience', 'No Experience Required')], default='no_experience', max_length=20)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('expenses_paid', models.BooleanField(default=False)),
                ('skills_required', models.TextField(blank=True)),
                ('skills_gained', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_posted', models.DateField()),
                ('application_url', models.URLField()),
                ('source', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobstract.employer')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-date_posted'],
            },
        ),
    ]
