# Generated by Django 4.2.15 on 2025-02-02 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_writer', '0014_remove_professionalsummary_cv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobstract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_writer.cvwriter')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobstract.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_date'],
                'unique_together': {('user', 'opportunity')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_received', 'Offer Received'), ('note_added', 'Note Added'), ('follow_up', 'Follow Up')], max_length=20)),
                ('event_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobstract.jobapplication')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
