"""
Career Field Definitions for Job Recommendation Engine
"""

CAREER_FIELDS = {
    "technology": [
        "developer",
        "engineer",
        "programmer",
        "software",
        "devops",
        "data scientist",
        "machine learning",
        "ai",
        "cybersecurity",
        "it",
        "systems",
        "architect",
        "coding",
    ],
    "finance": [
        "accountant",
        "accounting",
        "financial",
        "finance",
        "auditor",
        "bookkeeper",
        "tax",
        "payroll",
        "accounts",
        "treasury",
        "investment",
        "banking",
        "credit",
    ],
    "business": [
        "manager",
        "analyst",
        "consultant",
        "project manager",
        "business",
        "operations",
        "coordinator",
        "executive assistant",
        "hr",
    ],
    "retail": [
        "retail",
        "store manager",
        "shop",
        "merchandising",
        "visual merchandiser",
        "sales associate",
        "cashier",
        "customer service",
        "sales manager",
        "regional manager",
        "operations manager",
        "distribution manager",
        "warehouse",
        "logistics",
    ],
    "healthcare": [
        "nurse",
        "doctor",
        "medical",
        "healthcare",
        "clinical",
        "pharmacist",
        "therapist",
        "care",
        "health",
        "practitioner",
        "paramedic",
        "dental",
    ],
    "engineering": [
        "mechanical engineer",
        "civil engineer",
        "electrical engineer",
        "structural",
        "manufacturing",
        "industrial engineer",
        "technical engineer",
    ],
    "education": [
        "teacher",
        "lecturer",
        "professor",
        "tutor",
        "trainer",
        "instructor",
        "teaching assistant",
        "education",
        "academic",
    ],
    "legal": [
        "solicitor",
        "lawyer",
        "paralegal",
        "legal",
        "attorney",
        "barrister",
        "conveyancing",
    ],
    "compliance": [
        "compliance",
        "risk management",
        "risk analyst",
        "compliance officer",
        "risk officer",
        "audit",
        "regulatory",
        "governance",
    ],
    "creative": [
        "designer",
        "artist",
        "creative",
        "copywriter",
        "content writer",
        "graphic",
        "ux",
        "ui",
        "brand",
        "illustrator",
        "animator",
        "video editor",
    ],
    "marketing": [
        "marketing",
        "digital marketing",
        "seo",
        "sem",
        "social media",
        "content marketing",
        "brand manager",
        "marketing manager",
        "campaigns",
        "email marketing",
        "growth hacker",
        "marketing strategist",
    ],
    "photography": [
        "photographer",
        "photography",
        "videographer",
        "cinematographer",
        "photo editor",
        "camera operator",
        "video production",
    ],
    "media": [
        "journalist",
        "reporter",
        "editor",
        "producer",
        "broadcaster",
        "media",
        "communications",
        "public relations",
        "pr",
        "press officer",
    ],
    "hospitality": [
        "hotel",
        "hospitality",
        "restaurant",
        "chef",
        "cook",
        "waiter",
        "bartender",
        "catering",
        "tourism",
        "front desk",
        "concierge",
        "housekeeper",
        "sommelier",
    ],
    "construction": [
        "construction",
        "builder",
        "carpenter",
        "plumber",
        "electrician",
        "foreman",
        "site manager",
        "surveyor",
        "bricklayer",
        "joiner",
        "contractor",
        "scaffolder",
        "roofer",
    ],
    "manufacturing": [
        "production",
        "manufacturing",
        "assembly",
        "machinist",
        "quality control",
        "factory",
        "plant manager",
        "operations",
        "process engineer",
        "production supervisor",
    ],
    "sales": [
        "sales",
        "account manager",
        "business development",
        "sales representative",
        "account executive",
        "sales director",
        "commercial",
        "sales consultant",
    ],
    "transport": [
        "driver",
        "transport",
        "delivery",
        "logistics",
        "courier",
        "haulage",
        "fleet",
        "dispatcher",
        "truck driver",
        "van driver",
        "taxi driver",
    ],
    "public_sector": [
        "government",
        "public sector",
        "civil service",
        "local authority",
        "council",
        "policy",
        "public administration",
        "parliament",
    ],
    "charity": [
        "charity",
        "nonprofit",
        "non-profit",
        "fundraising",
        "community",
        "volunteer coordinator",
        "social work",
        "outreach",
        "ngo",
    ],
    "agriculture": [
        "farmer",
        "agriculture",
        "farm manager",
        "agricultural",
        "livestock",
        "horticulture",
        "gardener",
        "landscape",
        "groundskeeper",
        "arborist",
    ],
    "sports": [
        "coach",
        "personal trainer",
        "fitness",
        "sports",
        "athlete",
        "physiotherapist",
        "sports coach",
        "gym instructor",
        "wellness",
    ],
    "beauty": [
        "hairdresser",
        "beautician",
        "beauty therapist",
        "barber",
        "nail technician",
        "makeup artist",
        "aesthetician",
        "spa",
        "salon",
    ],
    "science": [
        "scientist",
        "researcher",
        "laboratory",
        "research",
        "biologist",
        "chemist",
        "physicist",
        "lab technician",
        "research assistant",
    ],
    "environmental": [
        "environmental",
        "sustainability",
        "conservation",
        "ecologist",
        "environmental consultant",
        "renewable energy",
        "waste management",
    ],
    "property": [
        "estate agent",
        "property",
        "real estate",
        "lettings",
        "property manager",
        "surveyor",
        "valuer",
        "facilities manager",
    ],
    "security": [
        "security",
        "security guard",
        "security officer",
        "door supervisor",
        "surveillance",
        "loss prevention",
        "bodyguard",
    ],
    "customer_service": [
        "customer service",
        "call centre",
        "contact centre",
        "customer support",
        "helpdesk",
        "support specialist",
        "customer care",
    ],
    "admin": [
        "administrative",
        "secretary",
        "receptionist",
        "office manager",
        "pa",
        "personal assistant",
        "clerk",
        "data entry",
    ],
    "aviation": [
        "pilot",
        "cabin crew",
        "flight attendant",
        "aviation",
        "aircraft",
        "air traffic",
        "aerospace",
    ],
    "maritime": [
        "maritime",
        "marine",
        "seafarer",
        "ship",
        "vessel",
        "port",
        "offshore",
        "naval",
    ],
    "insurance": [
        "insurance",
        "underwriter",
        "claims",
        "actuary",
        "insurance broker",
        "risk assessor",
    ],
    "telecommunications": [
        "telecommunications",
        "telecom",
        "network engineer",
        "telecommunications engineer",
        "fiber optic",
        "broadband",
    ],
    "automotive": [
        "mechanic",
        "automotive",
        "motor",
        "car technician",
        "vehicle",
        "mot tester",
        "auto electrician",
    ],
    "energy": [
        "energy",
        "utilities",
        "power",
        "electrical grid",
        "gas engineer",
        "renewable",
    ],
    "veterinary": [
        "veterinary",
        "vet",
        "animal care",
        "veterinarian",
        "vet nurse",
        "animal welfare",
    ],
    "pharmacy": [
        "pharmacist",
        "pharmacy",
        "pharmaceutical",
        "pharmacy technician",
        "dispenser",
    ],
    "architecture": [
        "architect",
        "architecture",
        "architectural",
        "urban planning",
        "town planner",
    ],
    "performing_arts": [
        "actor",
        "performer",
        "musician",
        "dancer",
        "theatre",
        "drama",
        "entertainment",
        "stage manager",
    ],
    "library": [
        "librarian",
        "library",
        "archivist",
        "information specialist",
    ],
    "recruitment": [
        "recruiter",
        "recruitment",
        "talent acquisition",
        "headhunter",
        "recruitment consultant",
    ],
}
