# Generated by Django 4.2.15 on 2025-03-21 05:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
