# Generated by Django 4.2.15 on 2025-03-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tldr",
            field=models.TextField(
                blank=True,
                help_text="TLDR summary of the article content",
                max_length=1000,
            ),
        ),
    ]
