# Generated by Django 4.2.15 on 2025-03-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_tldr"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog/images/%Y/%m/%d/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Image",
                "verbose_name_plural": "Blog Images",
                "ordering": ["-created_at"],
            },
        ),
    ]
