# Generated by Django 4.2.15 on 2025-03-22 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="share_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PostAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("unique_views", models.PositiveIntegerField(default=0)),
                ("avg_time_spent", models.DurationField(blank=True, null=True)),
                (
                    "bounce_rate",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of visitors who navigate away after viewing only this page",
                        null=True,
                    ),
                ),
                (
                    "referrers",
                    models.JSONField(
                        blank=True, default=dict, help_text="Referring sites/URLs"
                    ),
                ),
                (
                    "device_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Device type breakdown (mobile, desktop, tablet)",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Analytics",
                "verbose_name_plural": "Post Analytics",
            },
        ),
    ]
