# Generated by Django 4.2.15 on 2025-04-15 22:06

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_share_count_postanalytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogimage",
            name="caption",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogimage",
            name="image",
            field=models.ImageField(upload_to=blog.models.validate_image_path),
        ),
        migrations.AlterField(
            model_name="blogimage",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_images",
                to="blog.post",
            ),
        ),
    ]
