"""
Disposable Email Detection
Blocks temporary/throwaway email services to prevent abuse
"""

# Common disposable email domains
# Updated regularly from https://github.com/disposable/disposable-email-domains
DISPOSABLE_EMAIL_DOMAINS = {
    # Popular temporary email services
    "10minutemail.com",
    "10minutemail.net",
    "10minutemail.org",
    "guerrillamail.com",
    "guerrillamail.net",
    "guerrillamail.org",
    "mailinator.com",
    "mailinator2.com",
    "mailinator.net",
    "tempmail.com",
    "temp-mail.org",
    "temp-mail.io",
    "throwaway.email",
    "trashmail.com",
    "getnada.com",
    "maildrop.cc",
    "sharklasers.com",
    "grr.la",
    "fakeinbox.com",
    "yopmail.com",
    "yopmail.net",
    "emailondeck.com",
    "emltmp.com",
    "getairmail.com",
    "mailnesia.com",
    "mintemail.com",
    "mytempemail.com",
    "dispostable.com",
    "disposeamail.com",
    "throwawaymail.com",
    "spamgourmet.com",
    "mailcatch.com",
    "mailnator.com",
    "33mail.com",
    "anonymbox.com",
    "binkmail.com",
    "bobmail.info",
    "boxformail.in",
    "bugmenot.com",
    "deadaddress.com",
    "emailsensei.com",
    "emailtemporar.ro",
    "filzmail.com",
    "getonemail.com",
    "harakirimail.com",
    "incognitomail.com",
    "jetable.org",
    "keepmymail.com",
    "klzlk.com",
    "link2mail.net",
    "mailexpire.com",
    "mailforspam.com",
    "mailfreeonline.com",
    "mailin8r.com",
    "mailme.ir",
    "mailmoat.com",
    "mailnull.com",
    "mailsac.com",
    "mailtothis.com",
    "mailzi.ru",
    "mohmal.com",
    "monemail.fr.nf",
    "mt2009.com",
    "mytrashmail.com",
    "nada.email",
    "netmails.com",
    "nincsmail.hu",
    "no-spam.ws",
    "nomail.xl.cx",
    "nospam.ze.tc",
    "nospamfor.us",
    "objectmail.com",
    "oneoffemail.com",
    "onewaymail.com",
    "ordinaryamerican.net",
    "pookmail.com",
    "privacy.net",
    "proxymail.eu",
    "putthisinyourspamdatabase.com",
    "quickinbox.com",
    "rcpt.at",
    "recode.me",
    "recursor.net",
    "s0ny.net",
    "safersignup.de",
    "safetymail.info",
    "sendspamhere.com",
    "sharklasers.com",
    "shitmail.me",
    "shortmail.net",
    "sibmail.com",
    "smellfear.com",
    "snakemail.com",
    "spam.la",
    "spamavert.com",
    "spambob.com",
    "spambog.com",
    "spambooger.com",
    "spambox.us",
    "spamcannon.com",
    "spamcorptastic.com",
    "spamcowboy.com",
    "spamday.com",
    "spamex.com",
    "spamfree24.org",
    "spamgourmet.com",
    "spamhole.com",
    "spamify.com",
    "spaminator.de",
    "spamkill.info",
    "spaml.com",
    "spammotel.com",
    "spamobox.com",
    "spamslicer.com",
    "spamspot.com",
    "spamthis.co.uk",
    "spamtrail.com",
    "speed.1s.fr",
    "supergreatmail.com",
    "supermailer.jp",
    "suremail.info",
    "talkinator.com",
    "teleworm.com",
    "tempail.com",
    "tempalias.com",
    "tempe-mail.com",
    "tempemail.biz",
    "tempemail.com",
    "tempinbox.co.uk",
    "tempinbox.com",
    "tempmail.eu",
    "tempmail2.com",
    "tempomail.fr",
    "temporarily.de",
    "temporarioemail.com.br",
    "temporaryemail.net",
    "temporaryforwarding.com",
    "temporaryinbox.com",
    "thankyou2010.com",
    "thisisnotmyrealemail.com",
    "throwawayemailaddress.com",
    "tilien.com",
    "tmailinator.com",
    "tradermail.info",
    "trash-mail.at",
    "trash-mail.com",
    "trash-mail.de",
    "trash2009.com",
    "trashemail.de",
    "trashmail.at",
    "trashmail.me",
    "trashmail.net",
    "trashmail.org",
    "trashmail.ws",
    "trashmailer.com",
    "trashymail.com",
    "trialmail.de",
    "trillianpro.com",
    "twinmail.de",
    "uggsrock.com",
    "upliftnow.com",
    "uplipht.com",
    "venompen.com",
    "veryrealemail.com",
    "viditag.com",
    "viewcastmedia.com",
    "viewcastmedia.net",
    "viewcastmedia.org",
    "wadja.com",
    "walkmail.net",
    "webemail.me",
    "wegwerfadresse.de",
    "wegwerfemail.de",
    "wegwerpmailadres.nl",
    "wh4f.org",
    "whatiaas.com",
    "whatpaas.com",
    "whyspam.me",
    "willselfdestruct.com",
    "winemaven.info",
    "wronghead.com",
    "wuzup.net",
    "wuzupmail.net",
    "xagloo.com",
    "xemaps.com",
    "xents.com",
    "xmaily.com",
    "xoxy.net",
    "yapped.net",
    "yeah.net",
    "yep.it",
    "yogamaven.com",
    "yopmail.fr",
    "yuurok.com",
    "zehnminuten.de",
    "zippymail.info",
    "zoemail.net",
    "zomg.info",
    # Additional common ones
    "emailfake.com",
    "fakeemail.net",
    "fakemailgenerator.com",
    "fake-mail.com",
    "fake-box.com",
    "20minutemail.it",
    "anonbox.net",
    "anonymousemail.me",
    "armyspy.com",
    "bobmail.info",
    "cool.fr.nf",
    "courriel.fr.nf",
    "dodgeit.com",
    "dropmail.me",
    "e4ward.com",
    "email60.com",
    "emailias.com",
    "emailigo.de",
    "emailinfive.com",
    "emailmiser.com",
    "emailproxsy.com",
    "emailto.de",
    "emailxfer.com",
    "fastmail.fm",
    "fightallspam.com",
    "filzmail.com",
    "fixmail.tk",
    "flyspam.com",
    "frapmail.com",
    "gishpuppy.com",
    "guerrillamailblock.com",
    "h.mintemail.com",
    "hidemail.de",
    "hmamail.com",
    "imgof.com",
    "inboxclean.com",
    "instant-mail.de",
    "ip6.li",
    "irish2me.com",
    "iwi.net",
    "koszmail.pl",
    "lroid.com",
    "mail-temporaire.fr",
    "mail.by",
    "mail.mezimages.net",
    "mail2rss.org",
    "mailbidon.com",
    "mailbiz.biz",
    "mailblocks.com",
    "mailbucket.org",
    "mailcat.biz",
    "mailcatch.com",
    "maileater.com",
    "mailin8r.com",
    "mailimate.com",
    "mailinater.com",
    "mailinator.gq",
    "mailinator.info",
    "mailincubator.com",
    "mailismagic.com",
    "mailme.lv",
    "mailmetrash.com",
    "mailmoat.com",
    "mailms.com",
    "mailproxsy.com",
    "mailquack.com",
    "mailrock.biz",
    "mailscrap.com",
    "mailshell.com",
    "mailsiphon.com",
    "mailslite.com",
    "mailtemp.info",
    "mailtome.de",
    "mailtrix.net",
    "mailzilla.com",
    "mbx.cc",
    "mega.zik.dj",
    "meltmail.com",
    "mintemail.com",
    "moncourrier.fr.nf",
    "monemail.fr.nf",
    "mypartyclip.de",
    "myphantomemail.com",
    "mytempmail.com",
    "nabuma.com",
    "netmails.net",
    "neverbox.com",
    "no-spam.hu",
    "nobulk.com",
    "noclickemail.com",
    "nogmailspam.info",
    "nomail.pw",
    "nomail2me.com",
    "nospamthanks.info",
    "notmailinator.com",
    "nowhere.org",
    "nowmymail.com",
    "nurfuerspam.de",
    "nus.edu.sg",
    "objectmail.com",
    "obobbo.com",
    "odnorazovoe.ru",
    "oneoffemail.com",
    "onewaymail.com",
    "online.ms",
}


def is_disposable_email(email: str) -> bool:
    """
    Check if email is from a disposable email service.

    Args:
        email: Email address to check

    Returns:
        True if disposable, False otherwise
    """
    if not email or "@" not in email:
        return False

    try:
        domain = email.split("@")[-1].lower().strip()
        return domain in DISPOSABLE_EMAIL_DOMAINS
    except Exception:
        return False


def validate_email_for_cv_analysis(email: str) -> dict:
    """
    Validate email for CV analysis submission.

    Args:
        email: Email address to validate

    Returns:
        dict with 'valid' (bool) and 'error' (str) if invalid
    """
    import re

    email = email.strip().lower()

    # Basic format validation
    email_pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
    if not re.match(email_pattern, email):
        return {
            "valid": False,
            "error": "Invalid email format. Please enter a valid email address.",
        }

    # Check for disposable emails
    if is_disposable_email(email):
        return {
            "valid": False,
            "error": "Temporary email addresses are not allowed. Please use a permanent email address.",
        }

    # Check for common fake patterns
    fake_patterns = [
        r"^test@",
        r"^fake@",
        r"^dummy@",
        r"^spam@",
        r"^noreply@",
        r"^asdf@",
        r"^qwerty@",
        r"@test\.",
        r"@fake\.",
        r"@example\.",
    ]

    for pattern in fake_patterns:
        if re.search(pattern, email, re.IGNORECASE):
            return {"valid": False, "error": "Please use a real email address."}

    return {"valid": True}


def get_disposable_email_count() -> int:
    """Get the total number of blocked disposable domains."""
    return len(DISPOSABLE_EMAIL_DOMAINS)
