# Generated by Django 5.1.5 on 2025-01-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cvwriter",
            old_name="interests",
            new_name="interest",
        ),
    ]
