# Generated by Django 5.1.5 on 2025-01-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0002_rename_interests_cvwriter_interest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cvwriter",
            name="interest",
        ),
        migrations.RemoveField(
            model_name="cvwriter",
            name="professional_summary",
        ),
    ]
