# Generated by Django 5.1.5 on 2025-01-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0004_interest_professionalsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
    ]
