# Generated by Django 5.1.5 on 2025-01-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0005_language_is_custom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvwriter",
            name="additional_information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
