# Generated by Django 5.1.5 on 2025-01-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0006_alter_cvwriter_additional_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
