# Generated by Django 5.1.5 on 2025-01-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0007_alter_education_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
