# Generated by Django 5.1.5 on 2025-01-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0008_alter_experience_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="certificate_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
