# Generated by Django 5.1.5 on 2025-01-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0009_alter_certification_certificate_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="certificate_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
