# Generated by Django 5.1.5 on 2025-01-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0010_alter_certification_certificate_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvwriter",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cvwriter",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cvwriter",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cvwriter",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cvwriter",
            name="visibility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("shared", "Shared"),
                ],
                default="private",
                max_length=20,
                null=True,
            ),
        ),
    ]
