# Generated by Django 4.2.15 on 2025-01-26 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "cv_writer",
            "0011_cvwriter_description_cvwriter_slug_cvwriter_status_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CVImprovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("professional_summary", "Professional Summary"),
                            ("experience", "Experience"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("certifications", "Certifications"),
                            ("languages", "Languages"),
                            ("interests", "Interests"),
                        ],
                        max_length=50,
                    ),
                ),
                ("original_content", models.TextField()),
                ("improved_content", models.TextField()),
                (
                    "improvement_type",
                    models.CharField(
                        choices=[
                            ("minimal", "Quick Improvement"),
                            ("full", "Deep Improvement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tokens_used", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvements",
                        to="cv_writer.cvwriter",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
