# Generated by Django 4.2.15 on 2025-01-31 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_writer', '0013_professionalsummary_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalsummary',
            name='cv',
        ),
    ]
