# Generated by Django 4.2.15 on 2025-02-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_writer', '0014_remove_professionalsummary_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvwriter',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'CV Writers'},
        ),
        migrations.AddField(
            model_name='cvwriter',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='cv_writer.cvwriter'),
        ),
        migrations.AddField(
            model_name='cvwriter',
            name='version_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvwriter',
            name='version_purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
