# Generated by Django 4.2.15 on 2025-02-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_writer', '0015_alter_cvwriter_options_cvwriter_parent_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvwriter',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cvwriter',
            name='version_name',
            field=models.CharField(blank=True, default='Version 1', max_length=100, null=True),
        ),
    ]
