# Generated by Django 4.2.15 on 2025-02-03 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_writer', '0016_cvwriter_is_primary_alter_cvwriter_version_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvwriter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_versions', to=settings.AUTH_USER_MODEL),
        ),
    ]
