# Generated by Django 4.2.15 on 2025-03-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0017_alter_cvwriter_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalsummary",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professional_summary",
                to="cv_writer.cvwriter",
            ),
        ),
    ]
