# Generated by Django 4.2.15 on 2025-03-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0018_professionalsummary_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionalsummary",
            name="summary",
            field=models.TextField(help_text="Professional summary of the CV"),
        ),
    ]
