# Generated by Django 4.2.15 on 2025-04-18 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cv_writer", "0019_alter_professionalsummary_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("preview_image", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("modern", "Modern"),
                            ("classic", "Classic"),
                            ("creative", "Creative"),
                            ("professional", "Professional"),
                            ("technical", "Technical"),
                        ],
                        max_length=50,
                    ),
                ),
                ("has_color_options", models.BooleanField(default=False)),
                ("has_font_options", models.BooleanField(default=False)),
                ("has_layout_options", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CV Template",
                "verbose_name_plural": "CV Templates",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="cvwriter",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cvs",
                to="cv_writer.cvtemplate",
            ),
        ),
        migrations.CreateModel(
            name="CVTemplateSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_scheme", models.CharField(blank=True, max_length=50)),
                ("font_choice", models.CharField(blank=True, max_length=50)),
                ("layout_option", models.CharField(blank=True, max_length=50)),
                ("custom_css", models.TextField(blank=True)),
                ("custom_settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_selections",
                        to="cv_writer.cvwriter",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cv_writer.cvtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_selections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Selection",
                "verbose_name_plural": "Template Selections",
                "unique_together": {("user", "cv")},
            },
        ),
    ]
