# Generated by Django 4.2.15 on 2025-05-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0021_populate_initial_cv_templates"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language",
            old_name="language_level",
            new_name="language",
        ),
        migrations.RenameField(
            model_name="language",
            old_name="language_name",
            new_name="proficiency",
        ),
        migrations.RemoveField(
            model_name="language",
            name="is_custom",
        ),
        migrations.AddField(
            model_name="certification",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="cv_writer.cvwriter",
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="cv_writer.cvwriter",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="cv_writer.cvwriter",
            ),
        ),
    ]
