# Generated by Django 4.2.15 on 2025-05-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0022_rename_language_level_language_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="cv_writer.cvwriter",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experience",
                to="cv_writer.cvwriter",
            ),
        ),
        migrations.AddField(
            model_name="interest",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to="cv_writer.cvwriter",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="cv_writer.cvwriter",
            ),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_media",
                to="cv_writer.cvwriter",
            ),
        ),
    ]
