# Generated by Django 4.2.15 on 2025-10-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_cv_parser", "0012_emailverification_and_more"),
        (
            "cv_writer",
            "0023_education_cv_experience_cv_interest_cv_reference_cv_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cvwriter",
            name="original_parsed_cv",
            field=models.ForeignKey(
                blank=True,
                help_text="Original uploaded CV that was rewritten to create this CvWriter record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rewritten_versions",
                to="ai_cv_parser.parsedcv",
            ),
        ),
    ]
