# Generated by Django 4.2.15 on 2025-10-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0024_cvwriter_original_parsed_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvwriter",
            name="address",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="cvwriter",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="cvwriter",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
