# Generated by Django 4.2.15 on 2025-10-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0025_alter_cvwriter_address_alter_cvwriter_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="achievements",
            field=models.TextField(blank=True, default=""),
        ),
    ]
