# Generated by Django 4.2.15 on 2025-10-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0026_alter_experience_achievements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="certificate_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
