# Generated by Django 4.2.15 on 2025-10-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0027_alter_certification_certificate_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="certificate_name",
            field=models.CharField(max_length=200),
        ),
    ]
