# Generated by Django 4.2.15 on 2025-10-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0028_alter_certification_certificate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
