# Generated by Django 4.2.15 on 2025-10-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0029_alter_education_field_of_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="achievements",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full-time", "Full-time"),
                    ("Part-time", "Part-time"),
                    ("Contract", "Contract"),
                    ("Internship", "Internship"),
                    ("Freelance", "Freelance"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
