# Generated by Django 4.2.15 on 2025-10-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_writer", "0030_alter_experience_achievements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full-time", "Full-time"),
                    ("Part-time", "Part-time"),
                    ("Contract", "Contract"),
                    ("Temporary", "Temporary"),
                    ("Freelance", "Freelance"),
                    ("Self-employed", "Self-employed"),
                    ("Internship", "Internship"),
                    ("Apprenticeship", "Apprenticeship"),
                    ("Volunteer", "Volunteer"),
                    ("Seasonal", "Seasonal"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
